name: Linux CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libx11-dev libglu1-mesa-dev

    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure CMake
      shell: bash
      working-directory: build
      run: cmake .. -DBUILD_LIBTIFF=ON

    - name: Build
      shell: bash
      working-directory: build
      run: cmake --build .

    - name: Set execute permissions
      shell: bash
      run: chmod -R +x build/bin

    - name: Test
      shell: bash
      env:
        PATH: ${{github.workspace}}/build/bin:${{env.PATH}}
        RAYPATH: ${{github.workspace}}/src/common
      run: python test/run_tests.py