name: Windows CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up MSVC
      uses: microsoft/setup-msbuild@v1.1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure CMake
      shell: bash
      working-directory: build
      run: cmake .. -DBUILD_LIBTIFF=ON

    - name: Build
      shell: bash
      working-directory: build
      run: cmake --build . --config Release

    - name: Test
      shell: bash
      env:
        RAYPATH: src/common
      run: python test/run_tests.py -p build/bin